# - import_playbook: ansible/nginx.yml
- hosts: all
  roles:
    - amtega.environment
  vars:
    environment_config:
      LC_ALL: C
  become: true
  tasks:
    - name: Setup Apt
      ansible.builtin.command:
        cmd: apt update
    # - name: Install NGINX
    #   ansible.builtin.include_role:
    #     name: nginxinc.nginx
    # - name: Configure NGINX
    #   ansible.builtin.copy:
    #     src: ansible_data/etc/nginx/conf.d/upstream.conf
    #     dest: /etc/nginx/conf.d/upstream.conf
    - name: Install VFox
      ansible.builtin.shell:
        cmd: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox 
        creates: /usr/bin/vfox