# - import_playbook: ansible/nginx.yml
- hosts: localhost
  roles:
  vars:
  become: false    
  tasks:
    - ansible.builtin.shell:
        cmd: export "PATH=$PATH:{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/.asdf/bin:{{ ansible_env.HOME }}/.asdf/shims:{{ ansible_env.PATH }}" 
    - name: Install OS Dependencies
      become: true  
      ansible.builtin.package:
        name:
          - procps
          - iproute2
          - curl
          - wget
          - tar
          - perl
          - libpoe-perl 
          - cpanminus
          - lsof
          - net-tools
          - htop
    - name: Install CPAN Dependencies
      community.general.cpanm:
        name: Protocol::WebSocket
      